---
- name: Install Google Chrome using Chocolatey via Nexus repo
  hosts: all
  gather_facts: true
  vars:
    #nexus_choco_repo_name: nexus-chocolatey
    #nexus_choco_repo_url: http://192.168.64.41:8081/repository/chocolatey-nuget-proxy/

    chrome_msi_url: "https://dl.google.com/dl/chrome/install/extended/googlechromestandaloneenterprise_arm64.msi"
    temp_path: "/tmp/GoogleChromeARM64.msi"
    win_temp_path: "C:\\Temp\\chrome_arm64.msi"
    Package_name: "Google Chrome"
  tasks:
    - name: get Current Google Chrome installation version
      ansible.windows.win_shell: 'Get-Package | Where-Object { $_.Name -eq "{{ Package_name }}" } | Select-Object Name, Version'
      ignore_errors: yes
      register: chrome_version_before

    - name: Display Current Google Chrome Version
      ansible.builtin.debug:
        msg: "Current Google Chrome Version: {{ chrome_version_before.stdout_lines }}"
      ignore_errors: yes

    - name: Download Chrome ARM64 Offline Installer
      ansible.builtin.uri:
        url: "{{ chrome_msi_url }}"
        dest: "{{ temp_path }}"
        timeout: 60
      delegate_to: localhost

    - name: Ensure the "{{ win_temp_path | ansible.builtin.win_dirname }}" directory exists
      ansible.windows.win_file:
        path: "{{ win_temp_path | ansible.builtin.win_dirname }}"
        state: directory

    - name: copy from ansible to target machine
      ansible.windows.win_copy:
        src: "{{ temp_path }}"
        dest: "{{ win_temp_path }}"

    - name: Install Google Chrome (Silent)
      ansible.windows.win_package:
        path: "{{ win_temp_path }}"
        arguments: /qn /norestart
        state: present

    - name: get Current Google Chrome installation version
      ansible.windows.win_shell: 'Get-Package | Where-Object { $_.Name -eq "{{ Package_name }}" } | Select-Object Name, Version'
      ignore_errors: yes
      register: chrome_version_after

    - name: Cleanup Installer
      ansible.windows.win_file:
        path: "{{ win_temp_path }}"
        state: absent
    