---
- name: Get latest Google Chrome version from Chocolatey API
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Query Chocolatey API for latest Chrome version
      ansible.windows.win_uri:
        url: "https://community.chocolatey.org/api/v2/Packages()?$filter=Id eq 'googlechrome'&$orderby=Version desc&$top=1"
        method: GET
        return_content: yes
      register: choco_response

    - name: Extract Chrome version from API response
      ansible.builtin.set_fact:
        chrome_latest_version: "{{ choco_response.content | regex_search('<d:Version>([^<]+)</d:Version>', '\\1') }}"

    - name: Display latest Chrome version
      debug:
        msg: "Latest Google Chrome version available via Chocolatey: {{ chrome_latest_version }}"

