---
- name: setup a webserver on staging srever
  hosts: staging
  become: yes
  gather_facts: yes
  tasks:
    - name: Install Apache web server
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and enable Apache service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Open port 80 and 443 in the firewall
      ansible.builtin.firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 80
        - 443 

    - name: Check if welcome.conf exists
      ansible.builtin.stat:
        path: /etc/httpd/conf.d/welcome.conf
      register: welcome_conf

    - name: Rename welcome.conf to welcome.conf.old
      ansible.builtin.command:
        ansible.builtin.shell: "mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf.old"
      when: welcome_conf.stat.exists
      notify: restart httpd

  handlers:
    - name: restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
